name: Auto Scan Update

on:
  schedule:
    - cron: "0 */4 * * *" # Protidin 6 ghonta por por (UTC time)
  workflow_dispatch:      # Manual run korar option

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scanner
        run: python update_links.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Islam Rahul"
          git config --global user.email "rahul@example.com"
          git add channels.json last_id.txt
          git commit -m "Auto update scan results" || exit 0
          git push
          
